---
Name: pardot
After:
  - 'framework/*'
  - 'cms/*'
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - BluehouseGroup\Pardot\PardotTracker
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - BluehouseGroup\Pardot\PardotConfig

SilverStripe\Control\Director:
  rules:
    'pardot': 'BluehouseGroup\Pardot\PardotPage'
