---
Name: pardot
After:
  - 'framework/*'
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - BluehouseGroup\Pardot\PardotTracker
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - BluehouseGroup\Pardot\PardotConfig

SilverStripe\Control\Director:
  rules:
    'pardot': 'BluehouseGroup\Pardot\PardotPage'

SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.Pardot:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: 'Pardot'
